"""add created at to resource model

Revision ID: 947bfa6415d8
Revises: dd7f71af55f0
Create Date: 2024-06-20 10:35:32.924709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947bfa6415d8'
down_revision: Union[str, None] = 'dd7f71af55f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'created_at')
    # ### end Alembic commands ###
