"""Add description to Permission model

Revision ID: e0da94e48d52
Revises: 712431ccb76c
Create Date: 2024-06-21 11:01:57.981662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0da94e48d52'
down_revision: Union[str, None] = '712431ccb76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'description')
    # ### end Alembic commands ###
